### ISSUE TITLE
trainLSTM_1.py is not working due to problem of Reshape

### ISSUE THREAD

**Issue by jielabs** [MiracleStudio/VisualQA#1]
python trainLSTM_1.py
```
Traceback (most recent call last):
  File "trainLSTM_1.py", line 122, in <module>
    main()
  File "trainLSTM_1.py", line 59, in main
    image_model.add(Reshape(input_shape = (img_dim,), dims=(img_dim,)))
TypeError: __init__() takes exactly 2 arguments (1 given)
```
Perhaps the API has changed the interface.

**Comment by jielabs** [comment]
Fixed. Perhaps it was due to some API change in keras.
