### ISSUE TITLE
Cannot run evaluateLSTM.py using the pretrained LTSM model

### ISSUE THREAD

**Issue by jielabs** [MiracleStudio/VisualQA#2]
python evaluateLSTM.py -model ../models/lstm_1_num_hidden_units_lstm_512_num_hidden_units_mlp_1024_num_hidden_layers_mlp_3.json -weights ../models/lstm_1_num_hidden_units_lstm_512_num_hidden_units_mlp_1024_num_hidden_layers_mlp_3_epoch_070.hdf5 -results ../results/lstm_512_1024_3_ep70.txt

```
Traceback (most recent call last):
  File "evaluateLSTM.py", line 107, in <module>
    main()
  File "evaluateLSTM.py", line 21, in main
    model = model_from_json(open(args.model).read())
  File "/Users/jyang/anaconda/lib/python2.7/site-packages/keras/models.py", line 197, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/Users/jyang/anaconda/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 25, in layer_from_config
    class_name = config['class_name']
KeyError: 'class_name'
```

**Comment by jielabs** [comment]
It seems to me the model file has changed the format so keras cannot recognize it. The best solution would be to retrain the model.
